server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: gateway-service
    prefer-ip-address: true

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/toolrent-realm
          jwk-set-uri: http://keycloak:8080/realms/toolrent-realm/protocol/openid-connect/certs
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: client-service
          uri: lb://client-service
          predicates:
            - Path=/client/**

        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/employee/**

        - id: fee-service
          uri: lb://fee-service
          predicates:
            - Path=/fee/**

        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/inventory/**

        - id: kardex-service
          uri: lb://kardex-service
          predicates:
            - Path=/kardex/**

        - id: rent-service
          uri: lb://rent-service
          predicates:
            - Path=/rent/**

        - id: report-service
          uri: lb://report-service
          predicates:
            - Path=/report/**