server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 5
    service-url:
      default-zone: http://discovery-service:8761/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: client-service
          uri: lb://client-service
          predicates:
            - Path=/client/**
          filters:
            - StripPrefix=1

        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/employee/**

        - id: fee-service
          uri: lb://fee-service
          predicates:
            - Path=/fee/**

        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/inventory/**

        - id: kardex-service
          uri: lb://kardex-service
          predicates:
            - Path=/kardex/**

        - id: rent-service
          uri: lb://rent-service
          predicates:
            - Path=/rent/**

        - id: report-service
          uri: lb://report-service
          predicates:
            - Path=/report/**